name: localize_generator_keys
description: A CLI to extract hardcoded text and generate localization JSON.
version: 0.0.1
homepage: https://github.com/abdoelmorap/remove_unused_localizations_keys
repository: https://github.com/abdoelmorap/remove_unused_localizations_keys
issue_tracker: https://github.com/abdoelmorap/remove_unused_localizations_keys/issues

publisher:
  name: abdelrhmantolba.online
  email: AbdelrahmanTolba@protonmail.com
  website: https://abdelrhmantolba.online
  country: EG

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0


screenshots:
  - description: The localize_generator_keys package logo.
    path: screenshots/logo.png

executables:
  localize_generator_keys: localize_generator_keys